apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-ms
  name: auth-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-ms
    spec:
      containers:
        - image: southamerica-east1-docker.pkg.dev/microservice-tienda/product-ms/auth-ms
          name: auth-ms
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-db-secrets
                  key: auth-db
            - name: PORT
              value: "3003"
            - name: NATS_SERVERS
              value: "nats://nats"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-jwt-secreat
                  key: jwt_secret
          resources: {}
status: {}
